//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UT_OperaterMPDr2.userControl {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ucToolBarRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ucToolBarRES() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UT_OperaterMPDr2.userControl.ucToolBarRES", typeof(ucToolBarRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Connect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisConnect {
            get {
                return ResourceManager.GetString("DisConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Escape probe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Escape {
            get {
                return ResourceManager.GetString("Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize scanner に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Init {
            get {
                return ResourceManager.GetString("Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload recipe file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecipeUpload {
            get {
                return ResourceManager.GetString("RecipeUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save scan data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveData {
            get {
                return ResourceManager.GetString("SaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start scan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScanStart {
            get {
                return ResourceManager.GetString("ScanStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop scan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScanStop {
            get {
                return ResourceManager.GetString("ScanStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sage down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StageDown {
            get {
                return ResourceManager.GetString("StageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stage up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StageUp {
            get {
                return ResourceManager.GetString("StageUp", resourceCulture);
            }
        }
    }
}
