//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRecipeEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViewRecipeEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   using System.Windows;
        ///
        ///[assembly: ThemeInfo(
        ///    ResourceDictionaryLocation.None,            //where theme specific resource dictionaries are located
        ///                                                //(used if a resource is not found in the page,
        ///                                                // or application resource dictionaries)
        ///    ResourceDictionaryLocation.SourceAssembly   //where the generic resource dictionary is located
        ///                                                //(used if a resource i [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssemblyInfo {
            get {
                return ResourceManager.GetString("AssemblyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy data to clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyFuncEx {
            get {
                return ResourceManager.GetString("CopyFuncEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut data to clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CutFuncEx {
            get {
                return ResourceManager.GetString("CutFuncEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A/D Conversion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExADConvCap {
            get {
                return ResourceManager.GetString("ExADConvCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A-Scope に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExAScopeCap {
            get {
                return ResourceManager.GetString("ExAScopeCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PulserReceiver に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExPulserReceiverCap {
            get {
                return ResourceManager.GetString("ExPulserReceiverCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scan range に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExScanRangeCap {
            get {
                return ResourceManager.GetString("ExScanRangeCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scan setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExScanSetCap {
            get {
                return ResourceManager.GetString("ExScanSetCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipe Editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ch-A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridColNameChA {
            get {
                return ResourceManager.GetString("GridColNameChA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ch-B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridColNameChB {
            get {
                return ResourceManager.GetString("GridColNameChB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridColNameItem {
            get {
                return ResourceManager.GetString("GridColNameItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ScanAxis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridColNameScanAxis {
            get {
                return ResourceManager.GetString("GridColNameScanAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridColNameSetting {
            get {
                return ResourceManager.GetString("GridColNameSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StepAxis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridColNameStepAxis {
            get {
                return ResourceManager.GetString("GridColNameStepAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InfoCaption {
            get {
                return ResourceManager.GetString("InfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magnify に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MagnifyFuncEx {
            get {
                return ResourceManager.GetString("MagnifyFuncEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Material に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display(_D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenueDisplay {
            get {
                return ResourceManager.GetString("MenueDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magnify に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenueDisplay_Magnify {
            get {
                return ResourceManager.GetString("MenueDisplay_Magnify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reduce に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenueDisplay_Reduce {
            get {
                return ResourceManager.GetString("MenueDisplay_Reduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenueEdit {
            get {
                return ResourceManager.GetString("MenueEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenueEdit_Copy {
            get {
                return ResourceManager.GetString("MenueEdit_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenueEdit_Cut {
            get {
                return ResourceManager.GetString("MenueEdit_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenueEdit_Paste {
            get {
                return ResourceManager.GetString("MenueEdit_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenueFile {
            get {
                return ResourceManager.GetString("MenueFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenueFile_Exit {
            get {
                return ResourceManager.GetString("MenueFile_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenueFile_Open {
            get {
                return ResourceManager.GetString("MenueFile_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenueFile_Print {
            get {
                return ResourceManager.GetString("MenueFile_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenueFile_Save {
            get {
                return ResourceManager.GetString("MenueFile_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save with specified file name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenueFile_SpecSave {
            get {
                return ResourceManager.GetString("MenueFile_SpecSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenueHelp {
            get {
                return ResourceManager.GetString("MenueHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Guide に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenueHelp_Guide {
            get {
                return ResourceManager.GetString("MenueHelp_Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenueHelp_Ver {
            get {
                return ResourceManager.GetString("MenueHelp_Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting(_S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenueSetting {
            get {
                return ResourceManager.GetString("MenueSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenueSetting_Lang {
            get {
                return ResourceManager.GetString("MenueSetting_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Printing Finished に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoticePrintFinished {
            get {
                return ResourceManager.GetString("NoticePrintFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Recipi file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFuncEx {
            get {
                return ResourceManager.GetString("OpenFuncEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste data from clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PasteFuncEx {
            get {
                return ResourceManager.GetString("PasteFuncEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quit this application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QuitFuncEx {
            get {
                return ResourceManager.GetString("QuitFuncEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipi File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecipiFile {
            get {
                return ResourceManager.GetString("RecipiFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reduce に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReduceFuncEx {
            get {
                return ResourceManager.GetString("ReduceFuncEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Recipi file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveFuncEx {
            get {
                return ResourceManager.GetString("SaveFuncEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ultrasound Speed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ultrasound_Speed {
            get {
                return ResourceManager.GetString("Ultrasound_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Water に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
    }
}
